# -*- coding: utf-8 -*-

[package]
name = "letmeind"
description = "Authenticated port knocking - Server"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [ "Michael Büsch <m@bues.ch>" ]
homepage = "https://bues.ch/h/letmein"
repository = "https://github.com/mbuesch/letmein"
readme = "README.md"
categories = [ "authentication", "network-programming", "command-line-utilities", "cryptography" ]
keywords = [ "port-knocking", "port", "knock", "firewall", "nftables" ]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
letmein-conf = { path = "../letmein-conf" }
letmein-proto = { path = "../letmein-proto" }
letmein-systemd = { path = "../letmein-systemd" }
nftables = "0.4"
tokio = { version = "1", features = [ "rt", "net", "macros", "signal", "sync", "time" ] }

# vim: ts=4 sw=4 expandtab
