# -*- coding: utf-8 -*-

[package]
name = "letmeind"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [ "Michael Büsch <m@bues.ch>" ]
publish = false

[dependencies]
anyhow = "1"
bincode = "1"
clap = { version = "4", features = ["derive"] }
letmein-conf = { path = "../letmein-conf" }
letmein-proto = { path = "../letmein-proto" }
nftables = "0.4"
sd-notify = { git = "https://github.com/lnicola/sd-notify.git", rev = "5f9cbef17f33549c60d322342dead37fe11f18a7" }
tokio = { version = "1", features = [ "rt", "net", "macros", "signal", "sync", "time" ] }

# vim: ts=4 sw=4 expandtab
